export enum RoutePaths {
    Welcome = '/welcome',
    Setup = '/setup',
    SignUp = '/sign-up',
    Login = '/login',
    PrivacyPolicy = '/privacy-policy',
    Personas = '/personas',
    Wallets = '/wallets',
    WalletsTransfer = '/wallets/transfer',
    WalletsSwap = '/wallets/swap',
    WalletsRedPacket = '/wallets/red-packet',
    WalletsSell = '/wallets/sell',
    WalletsHistory = '/wallets/history',
    CreateMaskWallet = '/create-mask-wallet',
    CreateMaskWalletName = '/create-mask-wallet/name',
    Settings = '/settings',
    Plugins = '/plugins',
}
