export enum RoutePaths {
    Welcome = '/welcome',
    Register = '/register',
    SignUp = '/sign-up',
    Login = '/login',
    PasswordReset = '/password-reset',
    Personas = '/personas',
    Wallets = '/wallets',
    WalletsTransfer = '/wallets/transfer',
    WalletsSwap = '/wallets/swap',
    WalletsRedPacket = '/wallets/red-packet',
    WalletsSell = '/wallets/sell',
    WalletsHistory = '/wallets/history',
    Settings = '/settings',
    Plugins = '/plugins',
}
