// If your plugin also works in isolated dashboard, please also register it in
// packages/dashboard/src/initialization/plugins.ts

import '@masknet/plugin-example'
import '@masknet/plugin-flow'
import '../plugins/Wallet'
import '../plugins/EVM'
import '../plugins/RedPacket'
import '../plugins/ITO'
import '../plugins/Snapshot'
import '../plugins/Collectible'
import '../plugins/External'
import '../plugins/Transak'
import '../plugins/Gitcoin'
import '../plugins/Polls'
import '../plugins/FileService'
import '../plugins/VCent'
import '../plugins/Trader'
import '../plugins/dHEDGE'
import '../plugins/PoolTogether'
import '../plugins/GoodGhosting'
import '../plugins/UnlockProtocol'
import '../plugins/Avatar'
import '../plugins/Furucombo'
import '../plugins/MaskBox'
import '../plugins/Foundation'
import '../plugins/Profile'
import '../plugins/Pets'
import '../plugins/EVM'
// import '../plugins/NFT'
// import '../plugins/Airdrop'
