// This file is a JavaScript file because it's reference to the plugins should not be counted as a project reference.
// If your plugin also works in isolated dashboard, please also register it in
// packages/dashboard/src/initialization/plugins.ts

import '@masknet/plugin-example'
import '@masknet/plugin-debugger'
import '@masknet/plugin-flow'
import '@masknet/plugin-file-service'
import '@masknet/plugin-rss3'
import '@masknet/plugin-dao'
import '@masknet/plugin-solana'
import '@masknet/plugin-cyberconnect'
import '@masknet/plugin-go-plus-security'
import '../plugins/Wallet'
import '../plugins/EVM'
import '../plugins/RedPacket'
import '../plugins/ITO'
import '../plugins/Snapshot'
import '../plugins/Savings'
import '../plugins/Collectible'
import '../plugins/External'
import '../plugins/Transak'
import '../plugins/Gitcoin'
import '../plugins/Polls'
import '../plugins/VCent'
import '../plugins/Trader'
import '../plugins/dHEDGE'
import '../plugins/PoolTogether'
import '../plugins/GoodGhosting'
import '../plugins/UnlockProtocol'
import '../plugins/Avatar'
import '../plugins/Furucombo'
import '../plugins/MaskBox'
import '../plugins/NextID'
// import '../plugins/Profile'
import '../plugins/Pets'
import '../plugins/CryptoartAI'
import '../plugins/FindTruman'
import '../plugins/ArtBlocks'
