export const step1ActiveIcon = new URL('../assets/stepAssets/step1Active.png', import.meta.url)
export const step2DisableIcon = new URL('../assets/stepAssets/step2Disable.png', import.meta.url)
export const step2ActiveIcon = new URL('../assets/stepAssets/step2Active.png', import.meta.url)
export const stepSuccessIcon = new URL('../assets/stepAssets/stepSuccess.png', import.meta.url)
export const dividerDisableIcon = new URL('../assets/stepAssets/dividerDisable.png', import.meta.url)
export const dividerActiveIcon = new URL('../assets/stepAssets/dividerActive.png', import.meta.url)
export const dividerSuccessIcon = new URL('../assets/stepAssets/dividerDone.png', import.meta.url)
