const betTypeOdd: Record<
    number,
    {
        outcomeRegistryId: number
        marketRegistryId: number
        gamePeriodId: number
        gameTypeId: number
        gameVarietyId: number
        paramId: number
        teamPlayerId: number
    }
> = {
    1: {
        outcomeRegistryId: 180,
        marketRegistryId: 9,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    2: {
        outcomeRegistryId: 181,
        marketRegistryId: 9,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    3: {
        outcomeRegistryId: 7,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 96,
        teamPlayerId: 1,
    },
    4: {
        outcomeRegistryId: 8,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 32,
        teamPlayerId: 1,
    },
    5: {
        outcomeRegistryId: 7,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 94,
        teamPlayerId: 1,
    },
    6: {
        outcomeRegistryId: 8,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 6,
        teamPlayerId: 1,
    },
    7: {
        outcomeRegistryId: 7,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 36,
        teamPlayerId: 1,
    },
    8: {
        outcomeRegistryId: 8,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 5,
        teamPlayerId: 1,
    },
    9: {
        outcomeRegistryId: 7,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 7,
        teamPlayerId: 1,
    },
    10: {
        outcomeRegistryId: 8,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 4,
        teamPlayerId: 1,
    },
    11: {
        outcomeRegistryId: 7,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    12: {
        outcomeRegistryId: 8,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    13: {
        outcomeRegistryId: 7,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 4,
        teamPlayerId: 1,
    },
    14: {
        outcomeRegistryId: 8,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 7,
        teamPlayerId: 1,
    },
    15: {
        outcomeRegistryId: 7,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 5,
        teamPlayerId: 1,
    },
    16: {
        outcomeRegistryId: 8,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 36,
        teamPlayerId: 1,
    },
    17: {
        outcomeRegistryId: 7,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 6,
        teamPlayerId: 1,
    },
    18: {
        outcomeRegistryId: 8,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 94,
        teamPlayerId: 1,
    },
    19: {
        outcomeRegistryId: 7,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 32,
        teamPlayerId: 1,
    },
    20: {
        outcomeRegistryId: 8,
        marketRegistryId: 3,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 96,
        teamPlayerId: 1,
    },
    21: {
        outcomeRegistryId: 9,
        marketRegistryId: 4,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 4,
        teamPlayerId: 1,
    },
    22: {
        outcomeRegistryId: 10,
        marketRegistryId: 4,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 4,
        teamPlayerId: 1,
    },
    23: {
        outcomeRegistryId: 9,
        marketRegistryId: 4,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 5,
        teamPlayerId: 1,
    },
    24: {
        outcomeRegistryId: 10,
        marketRegistryId: 4,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 5,
        teamPlayerId: 1,
    },
    25: {
        outcomeRegistryId: 9,
        marketRegistryId: 4,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 6,
        teamPlayerId: 1,
    },
    26: {
        outcomeRegistryId: 10,
        marketRegistryId: 4,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 6,
        teamPlayerId: 1,
    },
    27: {
        outcomeRegistryId: 9,
        marketRegistryId: 4,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 32,
        teamPlayerId: 1,
    },
    28: {
        outcomeRegistryId: 10,
        marketRegistryId: 4,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 32,
        teamPlayerId: 1,
    },
    29: {
        outcomeRegistryId: 1,
        marketRegistryId: 1,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    30: {
        outcomeRegistryId: 2,
        marketRegistryId: 1,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    31: {
        outcomeRegistryId: 3,
        marketRegistryId: 1,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    32: {
        outcomeRegistryId: 10009,
        marketRegistryId: 19,
        gamePeriodId: 24,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    33: {
        outcomeRegistryId: 10010,
        marketRegistryId: 19,
        gamePeriodId: 24,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    34: {
        outcomeRegistryId: 10009,
        marketRegistryId: 19,
        gamePeriodId: 31,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    35: {
        outcomeRegistryId: 10010,
        marketRegistryId: 19,
        gamePeriodId: 31,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    36: {
        outcomeRegistryId: 10009,
        marketRegistryId: 19,
        gamePeriodId: 32,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    37: {
        outcomeRegistryId: 10010,
        marketRegistryId: 19,
        gamePeriodId: 32,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    38: {
        outcomeRegistryId: 4,
        marketRegistryId: 2,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    39: {
        outcomeRegistryId: 5,
        marketRegistryId: 2,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    40: {
        outcomeRegistryId: 6,
        marketRegistryId: 2,
        gamePeriodId: 1,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    41: {
        outcomeRegistryId: 10009,
        marketRegistryId: 19,
        gamePeriodId: 30,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
    42: {
        outcomeRegistryId: 10010,
        marketRegistryId: 19,
        gamePeriodId: 30,
        gameTypeId: 1,
        gameVarietyId: 1,
        paramId: 1,
        teamPlayerId: 1,
    },
}

export default betTypeOdd
