const gameTypeRegistry: Record<number, string> = {
    '1': 'Goal',
    '2': 'Corners',
    '3': 'Double',
    '4': 'Aces',
    '5': 'Ace',
    '6': 'Removal',
    '7': 'Penalty time',
    '8': 'Yellow cards',
    '9': 'Assist',
    '10': 'Cards',
    '11': 'Misses',
    '12': 'Shots on target',
    '13': 'Offside',
    '14': 'Fouls',
    '15': 'Shots on goal',
    '16': 'Additional rates',
    '17': 'Game series',
    '18': 'Free throws scored',
    '19': 'Scored two-point shots',
    '20': 'Scored three-point shots',
    '21': 'Rebounds',
    '22': 'Assists',
    '23': 'Turnovers',
    '24': 'Blocks',
    '25': 'Baron',
    '26': 'Double errors',
    '27': 'Posts and Crossbars',
    '28': 'Breaks',
    '29': 'Ball ownership percentage',
    '30': 'Replacements',
    '31': '1 game',
    '32': '2 game',
    '33': 'Shootouts',
    '34': 'Hits',
    '35': 'Intercepts',
    '36': 'Defensive rebound',
    '37': 'Offensive rebound',
    '38': 'Extra bullets',
    '39': 'Best by sets',
    '40': 'Alternative outcomes',
    '41': 'Express outcomes',
    '42': 'Cards. statistics',
    '43': 'Barrack',
    '44': 'Base',
    '45': 'Block',
    '46': 'Corner',
    '47': 'Double Double',
    '48': 'Dragon',
    '49': 'Duration Minute',
    '50': 'FieldGoal',
    '51': 'Fight',
    '52': 'First Blood',
    '53': 'Frame',
    '54': 'Game',
    '55': 'Hit',
    '56': 'Home Run',
    '57': 'Inhibitor',
    '58': 'Interception',
    '59': 'Kick Point',
    '60': 'Kill',
    '61': 'KillDouble',
    '62': 'KillPenta',
    '63': 'KillQuadra',
    '64': 'KillTriple',
    '65': 'Knife Kill',
    '66': 'Leg',
    '67': 'Longest Pass Completion Yards',
    '68': 'Longest Reception Yards',
    '69': 'Map',
    '70': 'Multiple',
    '71': 'Overtime',
    '72': 'Pass Attempt',
    '73': 'Pass Completion',
    '74': 'Passing Yard',
    '75': 'Pitching Out',
    '76': 'Point',
    '77': 'Point Rebound Assist',
    '78': 'Rebound',
    '79': 'Receiving Yard',
    '80': 'Reception',
    '81': 'Roshan',
    '82': 'Round',
    '83': 'Run',
    '84': 'Rushing Touchdown',
    '85': 'Rushing Yard',
    '86': 'Save',
    '87': 'Set',
    '88': 'Shot On Goal',
    '89': 'Steal Block',
    '90': 'Strikeout',
    '91': 'Three-point Field Goal',
    '92': 'Touchdown',
    '93': 'Touchdown Pass',
    '94': 'Touchdown Reception',
    '95': 'Tower',
    '96': 'Triple Double',
    '97': 'Turnover',
    '98': 'Turret',
    '99': 'Win',
    '10000': 'Maps',
    '10001': 'Rounds',
    '10002': 'Frags',
}

export default gameTypeRegistry
