const marketRegistry: Record<number, string> = {
    '1': 'Full time result',
    '2': 'Double chance',
    '3': 'Handicap',
    '4': 'Total',
    '5': 'Individual Total 1',
    '6': 'Individual Total 2',
    '7': 'Individual Total',
    '8': 'Scored',
    '9': 'Both Teams To Score',
    '10': 'Correct Score',
    '11': 'To Score',
    '14': 'Total Even',
    '15': 'Individual Total Even',
    '16': 'Individual To Score',
    '17': 'HT-FT',
    '18': 'European handicap (3w)',
    '19': 'Winner of match',
    '20': 'Winner of 1st map',
    '21': 'Winner of 2nd map',
    '22': 'Race To',
    '23': 'Will there be',
    '24': 'Who First',
}
export default marketRegistry
