const sportRegistry: Record<number, string> = {
    '1': 'Table Tennis',
    '2': 'Netball',
    '3': 'Horse Racing AntePost',
    '4': 'Athletics',
    '5': 'Gaelic Football',
    '6': 'Hurling',
    '7': 'Trotting',
    '8': 'Horse Racing',
    '9': 'Surfing',
    '10': 'Sailing',
    '11': 'Beach Soccer',
    '12': 'Motorsport',
    '13': 'Chess',
    '14': 'Golf',
    '15': 'Billiards',
    '16': 'Lottery',
    '17': 'Curling',
    '18': 'Water Polo',
    '19': 'Speedway',
    '20': 'Trotting AntePost',
    '21': 'Futsal',
    '22': 'Special bets',
    '23': 'Ski Jumping',
    '24': 'Skiing',
    '25': 'Rugby',
    '26': 'Volleyball',
    '27': 'Handball',
    '28': 'Baseball',
    '29': 'Boxing',
    '30': 'Formula 1',
    '31': 'Basketball',
    '32': 'Ice Hockey',
    '33': 'Football',
    '34': 'Snooker',
    '35': 'Australian Rules',
    '36': 'Martial Arts',
    '37': 'Biathlon',
    '38': 'Motorbikes',
    '39': 'Bicycle Racing',
    '40': 'Cricket',
    '41': 'Bowls',
    '42': 'TV-Games',
    '43': 'Darts',
    '44': 'American Football',
    '45': 'Tennis',
    '46': 'Badminton',
    '47': 'eSports',
    '48': 'Floorball',
    '49': 'Sumo',
    '50': 'Beach Volleyball',
    '51': 'Field Hockey',
    '52': 'Squash',
    '53': 'Crossfit',
    '54': 'Softball',
    '1000': 'Dota 2',
    '1001': 'CS:GO',
    '1002': 'League of Legends',
    '1003': 'StarCraft II',
}

export default sportRegistry
