addReviewers: true

addAssignees: false

reviewers:
  - Jack-Works
  - guanbinrui
  - septs

numberOfReviewers: 0

skipKeywords: # A list of keywords to be skipped the process that add reviewers if pull requests include it
  - wip
  - draft
