# https://github.com/probot/stale

daysUntilStale: 90
daysUntilClose: 7

exemptLabels: ["Discussion: Security"]

staleLabel: "Will Not Fix"

markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

limitPerRun: 30

only: issues
