// Please make sure you have registered your plugin UI at ./PluginUI
import './Wallet/messages'
import './RedPacket/helpers'
import './Gitcoin/constants'
import './FileService/utils'
import './Polls/utils'
import './Transak/messages'
import './Trader/messages'
import './Polls/utils'
import './Election2020/messages'
import './COTM/messages'
import './ITO/messages'
