packages:
  - packages/*
  - packages/typed-message/base
  - packages/typed-message/react
  - packages/plugins/*
  - packages/polyfills/types
  - packages/web3-hooks/base
  - packages/web3-hooks/evm
  - packages/web3-shared/base
  - packages/web3-shared/evm
  - packages/web3-shared/flow
  - packages/web3-shared/solana
'@dimensiondev:registry': https://npm.pkg.github.com/
ignoreScripts: true
onlyBuiltDependencies: []
overrides:
  '@emotion/styled': $@emotion/styled
  '@emotion/react': $@emotion/react
  '@mui/base': $@mui/base
  '@mui/icons-material': $@mui/icons-material
  '@mui/material': $@mui/material
  '@swc/core': $@swc/core
  '@protobufjs/inquire': 1.1.0
  '@splinetool/runtime': 0.9.342
  '@tanstack/react-query': ^5.49.2
  '@types/node': 22.13.9
  '@types/react': $@types/react
  '@types/react-dom': $@types/react-dom
  elliptic: 6.6.1
  glob-stream: 7.0.0
  react: $react
  react-dom: $react-dom
  reflect-metadata: 0.1.13
patchedDependencies:
  '@ceramicnetwork/rpc-transport@0.3.1': patches/@ceramicnetwork__rpc-transport@0.3.1.patch
  '@types/react-avatar-editor@13.0.2': patches/@types__react-avatar-editor@13.0.2.patch
  rss3-next@0.6.17: patches/rss3-next@0.6.17.patch
  '@types/react-highlight-words@0.20.0': patches/@types__react-highlight-words@0.20.0.patch
  '@cyberlab/cyberconnect@4.2.2': patches/@cyberlab__cyberconnect@4.2.2.patch
  reflect-metadata@0.1.13: patches/reflect-metadata@0.1.13.patch
  bloom-filters@3.0.0: patches/bloom-filters@3.0.0.patch
  urlcat@3.1.0: patches/urlcat@3.1.0.patch
  '@protobufjs/inquire@1.1.0': patches/@protobufjs__inquire@1.1.0.patch
  eslint-plugin-i@2.29.1: patches/eslint-plugin-i@2.29.1.patch
  react-use@17.5.0: patches/react-use@17.5.0.patch
  react-devtools-inline@5.3.0: patches/react-devtools-inline@5.3.0.patch
  '@splinetool/runtime@0.9.342': patches/@splinetool__runtime@0.9.342.patch
  '@scamsniffer/detector': patches/@scamsniffer__detector.patch
  gulp: patches/gulp.patch
  ts-results-es: patches/ts-results-es.patch
  '@lingui/cli': patches/@lingui__cli.patch
peerDependencyRules:
  ignoreMissing: []
  allowAny:
    - webpack
    - react
    - react-dom
    - '@types/react'
  allowedVersions: {}
