packages:
  - 'packages/*'
  - 'packages/polyfills/types'
  - 'packages/web3-shared/base'
  - 'packages/web3-shared/evm'
  - 'packages/web3-shared/flow'
  - 'packages/web3-shared/solana'
  - 'packages/plugins/*'
