# If you need to speedup webpack build, please also add the new package builds into
# webpack config.resolve.alias
packages:
  - 'packages/*'
  - 'packages/polyfills/*'
  - 'packages/web3-shared/*'
  - 'packages/plugins/*'
