# If you need to speedup webpack build, please also add the new package builds into
# webpack config.resolve.alias
packages:
  - 'packages/*'
  - 'packages/polyfills/types'
  - 'packages/web3-shared/base'
  - 'packages/web3-shared/evm'
  - 'packages/web3-shared/flow'
  - 'packages/web3-shared/solana'
  - 'packages/plugins/*'
