# If you need to speedup webpack build, please also add the new package builds into
# webpack config.resolve.alias
packages:
  - 'packages/test-serializer'
  - 'packages/empty'
  - 'packages/polyfills'
  - 'packages/polyfills/types'
  - 'packages/scripts'
  - 'packages/dashboard'
  - 'packages/mask'
  - 'packages/injected-script'
  - 'packages/mask-sdk'
  - 'packages/public-api'
  - 'packages/shared-base'
  - 'packages/shared'
  - 'packages/web3-kit'
  - 'packages/web3-providers'
  - 'packages/web3-constants'
  - 'packages/web3-contracts'
  - 'packages/web3-shared/base'
  - 'packages/web3-shared/evm'
  - 'packages/web3-shared/flow'
  - 'packages/web3-shared/solana'
  - 'packages/storybook-shared'
  - 'packages/icons'
  - 'packages/theme'
  - 'packages/plugin-infra'
  - 'packages/plugins/template'
  - 'packages/plugins/example'
  - 'packages/plugins/Debugger'
  - 'packages/plugins/Wallet'
  - 'packages/plugins/Flow'
  - 'packages/plugins/FileService'
  - 'packages/plugins/DAO'
  - 'packages/plugins/RSS3'
  - 'packages/plugins/Solana'
  - 'packages/external-plugin-previewer'
  - 'packages/backup-format'
  - 'packages/encryption'
  - 'packages/provider-proxy'
  - 'packages/plugins/Play'
