packages:
  - 'packages/cli-dev-build'
  - 'packages/dashboard'
  - 'packages/maskbook'
  - 'packages/shared'
  - 'packages/storybook-shared'
  - 'packages/theme'
  - 'packages/icons'
  - 'packages/contracts'
  - 'packages/locale-kit'
  - 'packages/polyfill'
