packages:
  - packages/*
  - packages/typed-message/base
  - packages/typed-message/react
  - packages/plugins/*
  - packages/polyfills/types
  - packages/web3-hooks/base
  - packages/web3-hooks/evm
  - packages/web3-shared/base
  - packages/web3-shared/evm
  - packages/web3-shared/flow
  - packages/web3-shared/solana
'@dimensiondev:registry': https://npm.pkg.github.com/
ignoreScripts: true
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200
# https://github.com/pnpm/pnpm/issues/10257
# minimumReleaseAge: 4320
minimumReleaseAge: 0
# minimumReleaseAgeExclude:
#   - package-name
allowBuilds: []
overrides:
  '@emotion/styled': $@emotion/styled
  '@emotion/react': $@emotion/react
  '@mui/base': $@mui/base
  '@mui/icons-material': $@mui/icons-material
  '@mui/material': $@mui/material
  '@swc/core': $@swc/core
  '@splinetool/runtime': 0.9.342
  '@tanstack/react-query': ^5.49.2
  '@types/node': 22.13.9
  '@types/react': $@types/react
  '@types/react-dom': $@types/react-dom
  elliptic: 6.6.1
  glob-stream: 7.0.0
  react: $react
  react-dom: $react-dom
  reflect-metadata: 0.1.13
  # by @scamsniffer/detector
  ts-jest: '-'
  ts-node: '-'
  # native-fetch imports undici with CVE, it no longer maintained for 5 years.
  # now Node.js has global fetch, no need.
  'native-fetch>undici': '-'
  # CVEs
  protobufjs: 7.6.5
  node-forge: 1.4.0
  fast-xml-parser: 5.7.0 # imported by @aws-sdk/*
  h3: 1.15.9
  js-yaml: 4.2.0
  'ws@8': 8.21.0
  'ws@7': 7.5.11
  'picomatch@2': 2.3.2
  'picomatch@4': 4.0.4
  'glob@10': 10.5.0
  'glob@11': 11.1.0
  lodash: 4.18.1
  lodash-es: 4.18.1
patchedDependencies:
  '@types/react-avatar-editor@13.0.2': patches/@types__react-avatar-editor@13.0.2.patch
  '@types/react-highlight-words@0.20.0': patches/@types__react-highlight-words@0.20.0.patch
  reflect-metadata@0.1.13: patches/reflect-metadata@0.1.13.patch
  bloom-filters@3.0.0: patches/bloom-filters@3.0.0.patch
  urlcat@3.1.0: patches/urlcat@3.1.0.patch
  eslint-plugin-i@2.29.1: patches/eslint-plugin-i@2.29.1.patch
  react-use@17.5.0: patches/react-use@17.5.0.patch
  react-devtools-inline@5.3.0: patches/react-devtools-inline@5.3.0.patch
  '@splinetool/runtime@0.9.342': patches/@splinetool__runtime@0.9.342.patch
  '@scamsniffer/detector': patches/@scamsniffer__detector.patch
  gulp: patches/gulp.patch
  ts-results-es: patches/ts-results-es.patch
  '@lingui/cli': patches/@lingui__cli.patch
  native-fetch@4.0.2: patches/native-fetch@4.0.2.patch
peerDependencyRules:
  ignoreMissing: []
  allowAny:
    - webpack
    - react
    - react-dom
    - '@types/react'
