export * from './entry-dom.js'

export {
    startPluginSiteAdaptor,
    useActivatedPluginsSiteAdaptor,
    useActivatedPluginSiteAdaptor,
    useActivatedPluginSiteAdaptorAny,
    useActivatedPluginsSiteAdaptorAny,
    useActivatedPluginSiteAdaptorMinimal,
    useActivatedPluginsSiteAdaptorMinimal,
    useActivatedPluginSiteAdaptorNotMinimal,
    useActivatedPluginsSiteAdaptorNotMinimal,
    useIsMinimalMode,
    checkIsMinimalMode,
} from './manager/site-adaptor.js'

export {
    type PostContext,
    type PostContextAuthor,
    type PostContextCoAuthor,
    type PostContextComment,
    type PostContextCreation,
    type PostContextActions,
    type PostInfo,
    PostInfoContext,
    usePostInfoDetails,
    usePostInfoPostIVIdentifier,
    usePostInfoRawMessage,
    usePostInfoMentionedLinks,
    usePostInfoAuthor,
    usePostInfoCoAuthors,
    usePostInfoNickname,
    usePostInfoEncryptComment,
    usePostInfoDecryptComment,
    usePostInfoURL,
    usePostInfoSource,
    usePostInfoPostMetadataImages,
    usePostInfoSite,
    type CompositionType,
    CompositionContext,
    Widget,
    type WidgetProps,
    getProfileCardTabContent,
    getProfileTabContent,
    getSearchResultContent,
    getSearchResultTabContent,
    getSearchResultTabs,
    getSettingsTabContent,
    getSearchResultContentForProfileTab,
    useAllPersonas,
    useCompositionContext,
    useCurrentPersonaInformation,
    useCurrentVisitingIdentity,
    useCurrentVisitingSocialIdentity,
    getLastRecognizedIdentity,
    useLastRecognizedIdentity,
    useLastRecognizedSocialIdentity,
    usePostLink,
    useSocialIdentity,
    useSiteThemeMode,
    useSocialIdentityByUserId,
    type __SiteAdaptorContext__,
    __setSiteAdaptorContext__,
} from './site-adaptor/index.js'

export { getBackgroundColor, isDark, toRGB, fromRGB, shade } from './utils/theme/color-tools.js'
