export * from './entry-dom.js'

export {
    startPluginSiteAdaptor,
    useActivatedPluginsSiteAdaptor,
    useActivatedPluginSiteAdaptor,
    useActivatedPluginSiteAdaptorAny,
    useActivatedPluginsSiteAdaptorAny,
    useActivatedPluginSiteAdaptorMinimal,
    useActivatedPluginsSiteAdaptorMinimal,
    useActivatedPluginSiteAdaptorNotMinimal,
    useActivatedPluginsSiteAdaptorNotMinimal,
    useIsMinimalMode,
    checkIsMinimalMode,
} from './manager/site-adaptor.js'

export {
    type PostContext,
    type PostContextAuthor,
    type PostContextComment,
    type PostContextCreation,
    type PostContextActions,
    type PostInfo,
    PostInfoContext,
    usePostInfoPostIVIdentifier,
    usePostInfoRawMessage,
    usePostInfoMentionedLinks,
    usePostInfoAuthor,
    usePostInfoNickname,
    usePostInfoEncryptComment,
    usePostInfoDecryptComment,
    usePostInfoURL,
    usePostInfoSource,
    usePostInfoPostMetadataImages,
    usePostInfoSite,
    usePostInfoHasMaskPayload,
    usePostInfoIdentifier,
    usePostInfoPostID,
    usePostInfoRootNode,
    usePostInfoVersion,
    usePostInfoIsAuthorOfPost,
    usePostInfoPublicShared,
    type CompositionType,
    CompositionContext,
    Widget,
    type WidgetProps,
    ProfileCardTabContent,
    ProfileTabContent,
    SearchResultContent,
    getSearchResultTabs,
    SearchResultContentForProfileTab,
    SearchResultTabContent,
    useAllPersonas,
    useCompositionContext,
    useCurrentPersonaInformation,
    useCurrentVisitingIdentity,
    useCurrentVisitingSocialIdentity,
    getLastRecognizedIdentity,
    useLastRecognizedIdentity,
    useLastRecognizedSocialIdentity,
    usePostLink,
    useSocialIdentity,
    getSiteThemeMode,
    useSocialIdentityByUserId,
    type __SiteAdaptorContext__,
    __setSiteAdaptorContext__,
} from './site-adaptor/index.js'

export { getBackgroundColor, isDark, toRGB, fromRGB, shade } from './utils/theme/color-tools.js'
