export {
    PLUGIN_IDENTIFIER,
    HD_PATH_WITHOUT_INDEX_ETHEREUM,
    JSON_RPC_ERROR_CODE,
    UPDATE_CHAIN_STATE_DELAY,
} from '@masknet/plugin-wallet'

export const OPENSEA_API_KEY = 'c38fe2446ee34f919436c32db480a2e3'
