// This file is a JavaScript file because it's reference to the plugins should not be counted as a project reference.
// If your plugin also works in isolated dashboard, please also register it in
// packages/dashboard/src/initialization/plugins.ts
import '@masknet/plugin-example'
import '@masknet/plugin-debugger'
import '@masknet/plugin-flow'
import '@masknet/plugin-file-service'
import '@masknet/plugin-rss3'
import '@masknet/plugin-dao'
import '@masknet/plugin-solana'
import '@masknet/plugin-cyberconnect'
import '@masknet/plugin-go-plus-security'
import '@masknet/plugin-cross-chain-bridge'
import '@masknet/plugin-scamsniffer'
import '../../src/plugins/Wallet'
import '@masknet/plugin-evm'
import '../../src/plugins/RedPacket'
import '../../src/plugins/ITO'
import '../../src/plugins/Snapshot'
import '../../src/plugins/Savings'
import '../../src/plugins/Collectible'
import '../../src/plugins/Transak'
import '../../src/plugins/Gitcoin'
import '../../src/plugins/VCent'
import '../../src/plugins/Trader'
import '../../src/plugins/Avatar'
import '../../src/plugins/Furucombo'
import '../../src/plugins/MaskBox'
import '../../src/plugins/NextID'
import '../../src/plugins/Pets'
import '../../src/plugins/Game'
import '../../src/plugins/CryptoartAI'
import '../../src/plugins/FindTruman'
import '../../src/plugins/ArtBlocks'
import '../../src/plugins/Referral'
import '../../src/plugins/Tips'
import '../../src/plugins/Approval'
import '@masknet/plugin-web3-profile'
// import '../../src/plugins/dHEDGE'
// import '../../src/plugins/External'
// import '../../src/plugins/Polls'
// import '../../src/plugins/PoolTogether'
// import '../../src/plugins/GoodGhosting'
// import '../../src/plugins/UnlockProtocol'
