// This file is a JavaScript file because it's reference to the plugins should not be counted as a project reference.
// If your plugin also works in isolated dashboard, please also register it in
// packages/dashboard/src/initialization/plugins.ts
import '@masknet/plugin-example'
import '@masknet/plugin-debugger'

import '../../src/plugins/WalletService/index.js'
import '../../src/plugins/RedPacket/index.js'
import '../../src/plugins/ITO/index.js'
import '../../src/plugins/Snapshot/index.js'
import '../../src/plugins/Savings/index.js'
import '../../src/plugins/Trader/index.js'
import '../../src/plugins/NextID/index.js'
import '../../src/plugins/ProfileCard/index.js'
import '../../src/plugins/Game/index.js'
import '../../src/plugins/Tips/index.js'

import '@masknet/plugin-wallet'
import '@masknet/plugin-evm'
import '@masknet/plugin-flow'
import '@masknet/plugin-solana'
import '@masknet/plugin-file-service'
import '@masknet/plugin-rss3'
import '@masknet/plugin-cyberconnect'
import '@masknet/plugin-go-plus-security'
import '@masknet/plugin-cross-chain-bridge'
import '@masknet/plugin-scamsniffer'
import '@masknet/plugin-web3-profile'
import '@masknet/plugin-handle'
import '@masknet/plugin-approval'
import '@masknet/plugin-smart-pay'
import '@masknet/plugin-gitcoin'
import '@masknet/plugin-scam-warning'
import '@masknet/plugin-collectible'
import '@masknet/plugin-transak'
import '@masknet/plugin-vcent'
import '@masknet/plugin-avatar/register'
import '@masknet/plugin-maskbox'
import '@masknet/plugin-claim'
import '@masknet/plugin-artblocks'
import '@masknet/plugin-pets'
import '@masknet/plugin-tips'
import '@masknet/plugin-external'
import '@masknet/plugin-game'
