/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from '../types'

interface EventOptions {
    filter?: object
    fromBlock?: BlockType
    topics?: string[]
}

export class Ito extends Contract {
    constructor(jsonInterface: any[], address?: string, options?: ContractOptions)
    clone(): Ito
    methods: {
        check_availability(
            id: string | number[],
        ): TransactionObject<{
            token_address: string
            balance: string
            total: string
            claimed: string
            expired: boolean
            ifclaimed: boolean
            0: string
            1: string
            2: string
            3: string
            4: boolean
            5: boolean
        }>

        claim(
            id: string | number[],
            password: string,
            _recipient: string,
            validation: string | number[],
        ): TransactionObject<string>

        contract_creator(): TransactionObject<string>

        destruct(id: string | number[]): TransactionObject<void>

        fill_pool(
            _hash: string | number[],
            _number: number | string,
            _duration: number | string,
            _exchange_addrs: string[],
            _ratios: (number | string)[],
            _token_addr: string,
            _total_tokens: number | string,
        ): TransactionObject<void>

        toBytes(a: string): TransactionObject<string>

        validRange(size: number | string, data: number | string): TransactionObject<boolean>
    }
    events: {
        ClaimSuccess: ContractEvent<{
            id: string
            claimer: string
            claimed_value: string
            token_address: string
            0: string
            1: string
            2: string
            3: string
        }>
        CreationSuccess: ContractEvent<{
            total: string
            id: string
            creator: string
            creation_time: string
            token_address: string
            0: string
            1: string
            2: string
            3: string
            4: string
        }>
        RefundSuccess: ContractEvent<{
            id: string
            token_address: string
            remaining_balance: string
            0: string
            1: string
            2: string
        }>
        allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
    }
}
