import { useAsync } from 'react-use'
import type { AsyncState } from 'react-use/lib/useAsyncFn'
import BigNumber from 'bignumber.js'
import type { SwapResponse, TradeComputed } from '../../types/index.js'
import { TradeStrategy } from '../../types/index.js'
import { ChainId, encodeContractTransaction, useTraderConstants } from '@masknet/web3-shared-evm'
import { useExchangeProxyContract } from '../../contracts/balancer/useExchangeProxyContract.js'
import type { ExchangeProxy } from '@masknet/web3-contracts/types/ExchangeProxy'
import { useTradeAmount } from './useTradeAmount.js'
import { SLIPPAGE_DEFAULT } from '../../constants/index.js'
import { NetworkPluginID } from '@masknet/shared-base'
import { useChainContext, useNetworkContext, useWeb3Connection, useWeb3State } from '@masknet/web3-hooks-base'

export function useTradeGasLimit(trade: TradeComputed<SwapResponse> | null): AsyncState<number> {
    const { account, chainId } = useChainContext()
    const { pluginID } = useNetworkContext()
    const { Others } = useWeb3State()
    const exchangeProxyContract = useExchangeProxyContract(
        pluginID === NetworkPluginID.PLUGIN_EVM ? (chainId as ChainId) : undefined,
    )
    const { BALANCER_ETH_ADDRESS } = useTraderConstants(
        pluginID === NetworkPluginID.PLUGIN_EVM ? (chainId as ChainId) : undefined,
    )
    const tradeAmount = useTradeAmount(trade, SLIPPAGE_DEFAULT)
    const connection = useWeb3Connection(pluginID)

    return useAsync(async () => {
        if (
            pluginID !== NetworkPluginID.PLUGIN_EVM ||
            !trade ||
            !trade.inputToken ||
            !trade.outputToken ||
            !exchangeProxyContract ||
            !BALANCER_ETH_ADDRESS ||
            !connection?.estimateTransaction
        )
            return 0

        const {
            swaps: [swaps],
        } = trade.trade_ as SwapResponse

        // cast the type to ignore the different type which was generated by typechain
        const swap_: Parameters<ExchangeProxy['methods']['multihopBatchSwapExactIn']>[0] = swaps.map((x) =>
            x.map(
                (y) =>
                    [
                        y.pool,
                        y.tokenIn,
                        y.tokenOut,
                        y.swapAmount,
                        y.limitReturnAmount,
                        y.maxPrice, // uint maxPrice
                    ] as [string, string, string, string, string, string],
            ),
        )

        const inputTokenAddress = Others?.isNativeTokenSchemaType(trade.inputToken?.schema)
            ? BALANCER_ETH_ADDRESS
            : trade.inputToken.address
        const outputTokenAddress = Others?.isNativeTokenSchemaType(trade.outputToken?.schema)
            ? BALANCER_ETH_ADDRESS
            : trade.outputToken.address

        // trade with the native token
        let transactionValue = '0'
        if (trade.strategy === TradeStrategy.ExactIn && Others?.isNativeTokenSchemaType(trade.inputToken?.schema))
            transactionValue = trade.inputAmount.toFixed()
        else if (
            trade.strategy === TradeStrategy.ExactOut &&
            Others?.isNativeTokenSchemaType(trade.outputToken?.schema)
        )
            transactionValue = trade.outputAmount.toFixed()

        const tx = await encodeContractTransaction(
            exchangeProxyContract,
            trade.strategy === TradeStrategy.ExactIn
                ? exchangeProxyContract.methods.multihopBatchSwapExactIn(
                      swap_,
                      inputTokenAddress,
                      outputTokenAddress,
                      trade.inputAmount.toFixed(),
                      tradeAmount.toFixed(),
                  )
                : exchangeProxyContract.methods.multihopBatchSwapExactOut(
                      swap_,
                      inputTokenAddress,
                      outputTokenAddress,
                      tradeAmount.toFixed(),
                  ),
            {
                from: account,
                value: transactionValue,
            },
        )

        const gas = await connection.estimateTransaction(tx)

        return new BigNumber(gas).toNumber()
    }, [
        trade,
        exchangeProxyContract,
        BALANCER_ETH_ADDRESS,
        tradeAmount,
        account,
        connection,
        pluginID,
        Others?.isNativeTokenSchemaType,
    ])
}
