export const NFTSCAN_URL = 'https://nftscan-proxy.r2d2.to'
export const NFTSCAN_BASE = 'https://www.nftscan.com'
export const NFTSCAN_BASE_SOLANA = 'https://solana.nftscan.com'
export const NFTSCAN_API = 'https://webapi.nftscan.com'
export const NFTSCAN_LOGO_BASE = 'https://logo.nftscan.com/logo'
export const NFTSCAN_LOGO_BASE_SOLANA = 'https://logo.nftscan.com/logo'
