export const POLL_META_KEY_1 = 'com.maskbook.poll:1'
export const PollGunServer = 'com.maskbook.plugin.polls'
export const PLUGIN_ID = 'com.maskbook.poll'
export const PLUGIN_NAME = 'Poll'
export const PLUGIN_ICON = '🗳️'
export const PLUGIN_DESCRIPTION = 'Easily create a Poll for receiving public votes.'
