import { createFungibleToken, createNonFungibleToken, isSameAddress } from '@masknet/web3-shared-base'
import {
    isValidDomain,
    isValidAddress,
    isZeroAddress,
    isNativeTokenAddress,
    isNativeTokenSchemaType,
    isFungibleTokenSchemaType,
    isNonFungibleTokenSchemaType,
    formatEthereumAddress,
    formatDomainName,
    formatTokenId,
    getTransactionSignature,
    type ChainId,
    type ProviderType,
    type NetworkType,
    type Transaction,
    type SchemaType,
    getNetworkPluginID,
    getDefaultChainId,
    getInvalidChainId,
    getDefaultNetworkType,
    getDefaultProviderType,
    getZeroAddress,
    getMaskTokenAddress,
    getNativeTokenAddress,
    getAverageBlockDelay,
    formatSchemaType,
    isValidChainId,
} from '@masknet/web3-shared-evm'
import type { OthersAPI_Base } from '../../Base/apis/OthersAPI.js'
import { ChainResolver, ExplorerResolver, ProviderResolver, NetworkResolver } from './ResolverAPI.js'

export const OthersAPI = {
    isSameAddress,
    chainResolver: ChainResolver,
    explorerResolver: ExplorerResolver,
    providerResolver: ProviderResolver,
    networkResolver: NetworkResolver,

    isValidDomain,
    isValidChainId,
    isValidAddress,
    isZeroAddress,
    isNativeTokenAddress,
    isNativeTokenSchemaType,
    isFungibleTokenSchemaType,
    isNonFungibleTokenSchemaType,

    getNetworkPluginID,
    getDefaultChainId,
    getInvalidChainId,
    getDefaultNetworkType,
    getDefaultProviderType,
    getZeroAddress,
    getMaskTokenAddress,
    getNativeTokenAddress,
    getTransactionSignature,
    getAverageBlockDelay,

    formatAddress: formatEthereumAddress,
    formatTokenId,
    formatDomainName,
    formatSchemaType,
    createNativeToken(chainId: ChainId) {
        return ChainResolver.nativeCurrency(chainId)
    },
    createFungibleToken,
    createNonFungibleToken,
} satisfies OthersAPI_Base<ChainId, SchemaType, ProviderType, NetworkType, Transaction>
