version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'monthly'

    default_reviewers:
      - 'Jack-Works'
      - 'guanbinrui'
      - 'septs'
    default_labels:
      - 'Dependencies'
