/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js'
import { Contract, ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { ContractEvent, Callback, TransactionObject, BlockType } from '../types'

interface EventOptions {
    filter?: object
    fromBlock?: BlockType
    topics?: string[]
}

export class Pausable extends Contract {
    constructor(jsonInterface: any[], address?: string, options?: ContractOptions)
    clone(): Pausable
    methods: {
        paused(): TransactionObject<boolean>
    }
    events: {
        Paused: ContractEvent<string>
        Unpaused: ContractEvent<string>
        allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter
    }
}
