/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers, EventFilter, Signer, BigNumber, BigNumberish, PopulatedTransaction } from 'ethers'
import { Contract, ContractTransaction, Overrides, CallOverrides } from '@ethersproject/contracts'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'
import { TypedEventFilter, TypedEvent, TypedListener } from './commons'

interface ERC721Interface extends ethers.utils.Interface {
    functions: {
        'supportsInterface(bytes4)': FunctionFragment
        'balanceOf(address)': FunctionFragment
        'ownerOf(uint256)': FunctionFragment
        'name()': FunctionFragment
        'symbol()': FunctionFragment
        'tokenURI(uint256)': FunctionFragment
        'baseURI()': FunctionFragment
        'tokenOfOwnerByIndex(address,uint256)': FunctionFragment
        'totalSupply()': FunctionFragment
        'tokenByIndex(uint256)': FunctionFragment
        'approve(address,uint256)': FunctionFragment
        'getApproved(uint256)': FunctionFragment
        'setApprovalForAll(address,bool)': FunctionFragment
        'isApprovedForAll(address,address)': FunctionFragment
        'transferFrom(address,address,uint256)': FunctionFragment
        'safeTransferFrom(address,address,uint256)': FunctionFragment
    }

    encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string
    encodeFunctionData(functionFragment: 'balanceOf', values: [string]): string
    encodeFunctionData(functionFragment: 'ownerOf', values: [BigNumberish]): string
    encodeFunctionData(functionFragment: 'name', values?: undefined): string
    encodeFunctionData(functionFragment: 'symbol', values?: undefined): string
    encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string
    encodeFunctionData(functionFragment: 'baseURI', values?: undefined): string
    encodeFunctionData(functionFragment: 'tokenOfOwnerByIndex', values: [string, BigNumberish]): string
    encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string
    encodeFunctionData(functionFragment: 'tokenByIndex', values: [BigNumberish]): string
    encodeFunctionData(functionFragment: 'approve', values: [string, BigNumberish]): string
    encodeFunctionData(functionFragment: 'getApproved', values: [BigNumberish]): string
    encodeFunctionData(functionFragment: 'setApprovalForAll', values: [string, boolean]): string
    encodeFunctionData(functionFragment: 'isApprovedForAll', values: [string, string]): string
    encodeFunctionData(functionFragment: 'transferFrom', values: [string, string, BigNumberish]): string
    encodeFunctionData(functionFragment: 'safeTransferFrom', values: [string, string, BigNumberish]): string

    decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'baseURI', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'tokenOfOwnerByIndex', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'tokenByIndex', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'safeTransferFrom', data: BytesLike): Result

    events: {
        'Approval(address,address,uint256)': EventFragment
        'ApprovalForAll(address,address,bool)': EventFragment
        'Transfer(address,address,uint256)': EventFragment
    }

    getEvent(nameOrSignatureOrTopic: 'Approval'): EventFragment
    getEvent(nameOrSignatureOrTopic: 'ApprovalForAll'): EventFragment
    getEvent(nameOrSignatureOrTopic: 'Transfer'): EventFragment
}

export class ERC721 extends Contract {
    connect(signerOrProvider: Signer | Provider | string): this
    attach(addressOrName: string): this
    deployed(): Promise<this>

    listeners<EventArgsArray extends Array<any>, EventArgsObject>(
        eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>,
    ): Array<TypedListener<EventArgsArray, EventArgsObject>>
    off<EventArgsArray extends Array<any>, EventArgsObject>(
        eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
        listener: TypedListener<EventArgsArray, EventArgsObject>,
    ): this
    on<EventArgsArray extends Array<any>, EventArgsObject>(
        eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
        listener: TypedListener<EventArgsArray, EventArgsObject>,
    ): this
    once<EventArgsArray extends Array<any>, EventArgsObject>(
        eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
        listener: TypedListener<EventArgsArray, EventArgsObject>,
    ): this
    removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
        eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
        listener: TypedListener<EventArgsArray, EventArgsObject>,
    ): this
    removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
        eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    ): this

    listeners(eventName?: string): Array<Listener>
    off(eventName: string, listener: Listener): this
    on(eventName: string, listener: Listener): this
    once(eventName: string, listener: Listener): this
    removeListener(eventName: string, listener: Listener): this
    removeAllListeners(eventName?: string): this

    queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
        event: TypedEventFilter<EventArgsArray, EventArgsObject>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined,
    ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>

    interface: ERC721Interface

    functions: {
        supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<[boolean]>

        'supportsInterface(bytes4)'(interfaceId: BytesLike, overrides?: CallOverrides): Promise<[boolean]>

        balanceOf(owner: string, overrides?: CallOverrides): Promise<[BigNumber]>

        'balanceOf(address)'(owner: string, overrides?: CallOverrides): Promise<[BigNumber]>

        ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<[string]>

        'ownerOf(uint256)'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<[string]>

        name(overrides?: CallOverrides): Promise<[string]>

        'name()'(overrides?: CallOverrides): Promise<[string]>

        symbol(overrides?: CallOverrides): Promise<[string]>

        'symbol()'(overrides?: CallOverrides): Promise<[string]>

        tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<[string]>

        'tokenURI(uint256)'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<[string]>

        baseURI(overrides?: CallOverrides): Promise<[string]>

        'baseURI()'(overrides?: CallOverrides): Promise<[string]>

        tokenOfOwnerByIndex(owner: string, index: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>

        'tokenOfOwnerByIndex(address,uint256)'(
            owner: string,
            index: BigNumberish,
            overrides?: CallOverrides,
        ): Promise<[BigNumber]>

        totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>

        'totalSupply()'(overrides?: CallOverrides): Promise<[BigNumber]>

        tokenByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>

        'tokenByIndex(uint256)'(index: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>

        approve(to: string, tokenId: BigNumberish, overrides?: Overrides): Promise<ContractTransaction>

        'approve(address,uint256)'(
            to: string,
            tokenId: BigNumberish,
            overrides?: Overrides,
        ): Promise<ContractTransaction>

        getApproved(tokenId: BigNumberish, overrides?: CallOverrides): Promise<[string]>

        'getApproved(uint256)'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<[string]>

        setApprovalForAll(operator: string, approved: boolean, overrides?: Overrides): Promise<ContractTransaction>

        'setApprovalForAll(address,bool)'(
            operator: string,
            approved: boolean,
            overrides?: Overrides,
        ): Promise<ContractTransaction>

        isApprovedForAll(owner: string, operator: string, overrides?: CallOverrides): Promise<[boolean]>

        'isApprovedForAll(address,address)'(
            owner: string,
            operator: string,
            overrides?: CallOverrides,
        ): Promise<[boolean]>

        transferFrom(
            from: string,
            to: string,
            tokenId: BigNumberish,
            overrides?: Overrides,
        ): Promise<ContractTransaction>

        'transferFrom(address,address,uint256)'(
            from: string,
            to: string,
            tokenId: BigNumberish,
            overrides?: Overrides,
        ): Promise<ContractTransaction>

        'safeTransferFrom(address,address,uint256)'(
            from: string,
            to: string,
            tokenId: BigNumberish,
            overrides?: Overrides,
        ): Promise<ContractTransaction>

        'safeTransferFrom(address,address,uint256,bytes)'(
            from: string,
            to: string,
            tokenId: BigNumberish,
            _data: BytesLike,
            overrides?: Overrides,
        ): Promise<ContractTransaction>
    }

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>

    'supportsInterface(bytes4)'(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>

    'balanceOf(address)'(owner: string, overrides?: CallOverrides): Promise<BigNumber>

    ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

    'ownerOf(uint256)'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

    name(overrides?: CallOverrides): Promise<string>

    'name()'(overrides?: CallOverrides): Promise<string>

    symbol(overrides?: CallOverrides): Promise<string>

    'symbol()'(overrides?: CallOverrides): Promise<string>

    tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

    'tokenURI(uint256)'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

    baseURI(overrides?: CallOverrides): Promise<string>

    'baseURI()'(overrides?: CallOverrides): Promise<string>

    tokenOfOwnerByIndex(owner: string, index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'tokenOfOwnerByIndex(address,uint256)'(
        owner: string,
        index: BigNumberish,
        overrides?: CallOverrides,
    ): Promise<BigNumber>

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>

    'totalSupply()'(overrides?: CallOverrides): Promise<BigNumber>

    tokenByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'tokenByIndex(uint256)'(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    approve(to: string, tokenId: BigNumberish, overrides?: Overrides): Promise<ContractTransaction>

    'approve(address,uint256)'(to: string, tokenId: BigNumberish, overrides?: Overrides): Promise<ContractTransaction>

    getApproved(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

    'getApproved(uint256)'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

    setApprovalForAll(operator: string, approved: boolean, overrides?: Overrides): Promise<ContractTransaction>

    'setApprovalForAll(address,bool)'(
        operator: string,
        approved: boolean,
        overrides?: Overrides,
    ): Promise<ContractTransaction>

    isApprovedForAll(owner: string, operator: string, overrides?: CallOverrides): Promise<boolean>

    'isApprovedForAll(address,address)'(owner: string, operator: string, overrides?: CallOverrides): Promise<boolean>

    transferFrom(from: string, to: string, tokenId: BigNumberish, overrides?: Overrides): Promise<ContractTransaction>

    'transferFrom(address,address,uint256)'(
        from: string,
        to: string,
        tokenId: BigNumberish,
        overrides?: Overrides,
    ): Promise<ContractTransaction>

    'safeTransferFrom(address,address,uint256)'(
        from: string,
        to: string,
        tokenId: BigNumberish,
        overrides?: Overrides,
    ): Promise<ContractTransaction>

    'safeTransferFrom(address,address,uint256,bytes)'(
        from: string,
        to: string,
        tokenId: BigNumberish,
        _data: BytesLike,
        overrides?: Overrides,
    ): Promise<ContractTransaction>

    callStatic: {
        supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>

        'supportsInterface(bytes4)'(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>

        balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>

        'balanceOf(address)'(owner: string, overrides?: CallOverrides): Promise<BigNumber>

        ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

        'ownerOf(uint256)'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

        name(overrides?: CallOverrides): Promise<string>

        'name()'(overrides?: CallOverrides): Promise<string>

        symbol(overrides?: CallOverrides): Promise<string>

        'symbol()'(overrides?: CallOverrides): Promise<string>

        tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

        'tokenURI(uint256)'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

        baseURI(overrides?: CallOverrides): Promise<string>

        'baseURI()'(overrides?: CallOverrides): Promise<string>

        tokenOfOwnerByIndex(owner: string, index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        'tokenOfOwnerByIndex(address,uint256)'(
            owner: string,
            index: BigNumberish,
            overrides?: CallOverrides,
        ): Promise<BigNumber>

        totalSupply(overrides?: CallOverrides): Promise<BigNumber>

        'totalSupply()'(overrides?: CallOverrides): Promise<BigNumber>

        tokenByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        'tokenByIndex(uint256)'(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        approve(to: string, tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>

        'approve(address,uint256)'(to: string, tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>

        getApproved(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

        'getApproved(uint256)'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>

        setApprovalForAll(operator: string, approved: boolean, overrides?: CallOverrides): Promise<void>

        'setApprovalForAll(address,bool)'(operator: string, approved: boolean, overrides?: CallOverrides): Promise<void>

        isApprovedForAll(owner: string, operator: string, overrides?: CallOverrides): Promise<boolean>

        'isApprovedForAll(address,address)'(
            owner: string,
            operator: string,
            overrides?: CallOverrides,
        ): Promise<boolean>

        transferFrom(from: string, to: string, tokenId: BigNumberish, overrides?: CallOverrides): Promise<void>

        'transferFrom(address,address,uint256)'(
            from: string,
            to: string,
            tokenId: BigNumberish,
            overrides?: CallOverrides,
        ): Promise<void>

        'safeTransferFrom(address,address,uint256)'(
            from: string,
            to: string,
            tokenId: BigNumberish,
            overrides?: CallOverrides,
        ): Promise<void>

        'safeTransferFrom(address,address,uint256,bytes)'(
            from: string,
            to: string,
            tokenId: BigNumberish,
            _data: BytesLike,
            overrides?: CallOverrides,
        ): Promise<void>
    }

    filters: {
        Approval(
            owner: string | null,
            approved: string | null,
            tokenId: BigNumberish | null,
        ): TypedEventFilter<[string, string, BigNumber], { owner: string; approved: string; tokenId: BigNumber }>

        ApprovalForAll(
            owner: string | null,
            operator: string | null,
            approved: null,
        ): TypedEventFilter<[string, string, boolean], { owner: string; operator: string; approved: boolean }>

        Transfer(
            from: string | null,
            to: string | null,
            tokenId: BigNumberish | null,
        ): TypedEventFilter<[string, string, BigNumber], { from: string; to: string; tokenId: BigNumber }>
    }

    estimateGas: {
        supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

        'supportsInterface(bytes4)'(interfaceId: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

        balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>

        'balanceOf(address)'(owner: string, overrides?: CallOverrides): Promise<BigNumber>

        ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        'ownerOf(uint256)'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        name(overrides?: CallOverrides): Promise<BigNumber>

        'name()'(overrides?: CallOverrides): Promise<BigNumber>

        symbol(overrides?: CallOverrides): Promise<BigNumber>

        'symbol()'(overrides?: CallOverrides): Promise<BigNumber>

        tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        'tokenURI(uint256)'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        baseURI(overrides?: CallOverrides): Promise<BigNumber>

        'baseURI()'(overrides?: CallOverrides): Promise<BigNumber>

        tokenOfOwnerByIndex(owner: string, index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        'tokenOfOwnerByIndex(address,uint256)'(
            owner: string,
            index: BigNumberish,
            overrides?: CallOverrides,
        ): Promise<BigNumber>

        totalSupply(overrides?: CallOverrides): Promise<BigNumber>

        'totalSupply()'(overrides?: CallOverrides): Promise<BigNumber>

        tokenByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        'tokenByIndex(uint256)'(index: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        approve(to: string, tokenId: BigNumberish, overrides?: Overrides): Promise<BigNumber>

        'approve(address,uint256)'(to: string, tokenId: BigNumberish, overrides?: Overrides): Promise<BigNumber>

        getApproved(tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        'getApproved(uint256)'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        setApprovalForAll(operator: string, approved: boolean, overrides?: Overrides): Promise<BigNumber>

        'setApprovalForAll(address,bool)'(
            operator: string,
            approved: boolean,
            overrides?: Overrides,
        ): Promise<BigNumber>

        isApprovedForAll(owner: string, operator: string, overrides?: CallOverrides): Promise<BigNumber>

        'isApprovedForAll(address,address)'(
            owner: string,
            operator: string,
            overrides?: CallOverrides,
        ): Promise<BigNumber>

        transferFrom(from: string, to: string, tokenId: BigNumberish, overrides?: Overrides): Promise<BigNumber>

        'transferFrom(address,address,uint256)'(
            from: string,
            to: string,
            tokenId: BigNumberish,
            overrides?: Overrides,
        ): Promise<BigNumber>

        'safeTransferFrom(address,address,uint256)'(
            from: string,
            to: string,
            tokenId: BigNumberish,
            overrides?: Overrides,
        ): Promise<BigNumber>

        'safeTransferFrom(address,address,uint256,bytes)'(
            from: string,
            to: string,
            tokenId: BigNumberish,
            _data: BytesLike,
            overrides?: Overrides,
        ): Promise<BigNumber>
    }

    populateTransaction: {
        supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

        'supportsInterface(bytes4)'(interfaceId: BytesLike, overrides?: CallOverrides): Promise<PopulatedTransaction>

        balanceOf(owner: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

        'balanceOf(address)'(owner: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

        ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

        'ownerOf(uint256)'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

        name(overrides?: CallOverrides): Promise<PopulatedTransaction>

        'name()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

        symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>

        'symbol()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

        tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

        'tokenURI(uint256)'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

        baseURI(overrides?: CallOverrides): Promise<PopulatedTransaction>

        'baseURI()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

        tokenOfOwnerByIndex(
            owner: string,
            index: BigNumberish,
            overrides?: CallOverrides,
        ): Promise<PopulatedTransaction>

        'tokenOfOwnerByIndex(address,uint256)'(
            owner: string,
            index: BigNumberish,
            overrides?: CallOverrides,
        ): Promise<PopulatedTransaction>

        totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>

        'totalSupply()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

        tokenByIndex(index: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

        'tokenByIndex(uint256)'(index: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

        approve(to: string, tokenId: BigNumberish, overrides?: Overrides): Promise<PopulatedTransaction>

        'approve(address,uint256)'(
            to: string,
            tokenId: BigNumberish,
            overrides?: Overrides,
        ): Promise<PopulatedTransaction>

        getApproved(tokenId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

        'getApproved(uint256)'(tokenId: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

        setApprovalForAll(operator: string, approved: boolean, overrides?: Overrides): Promise<PopulatedTransaction>

        'setApprovalForAll(address,bool)'(
            operator: string,
            approved: boolean,
            overrides?: Overrides,
        ): Promise<PopulatedTransaction>

        isApprovedForAll(owner: string, operator: string, overrides?: CallOverrides): Promise<PopulatedTransaction>

        'isApprovedForAll(address,address)'(
            owner: string,
            operator: string,
            overrides?: CallOverrides,
        ): Promise<PopulatedTransaction>

        transferFrom(
            from: string,
            to: string,
            tokenId: BigNumberish,
            overrides?: Overrides,
        ): Promise<PopulatedTransaction>

        'transferFrom(address,address,uint256)'(
            from: string,
            to: string,
            tokenId: BigNumberish,
            overrides?: Overrides,
        ): Promise<PopulatedTransaction>

        'safeTransferFrom(address,address,uint256)'(
            from: string,
            to: string,
            tokenId: BigNumberish,
            overrides?: Overrides,
        ): Promise<PopulatedTransaction>

        'safeTransferFrom(address,address,uint256,bytes)'(
            from: string,
            to: string,
            tokenId: BigNumberish,
            _data: BytesLike,
            overrides?: Overrides,
        ): Promise<PopulatedTransaction>
    }
}
