export const ARWEAVE_GATEWAY = 'https://arweave.net/'
export const IPFS_GATEWAY = 'https://ipfs.io/ipfs/'
export const FIREFLY_SITE_URL = 'https://firefly.mask.social'
export const HEY_IPFS_GW_URL = 'https://gw.ipfs-lens.dev/ipfs'
export const HEY_IMAGEKIT_URL = 'https://ik.imagekit.io/lensterimg'
