export const PLUGIN_ID = 'com.maskbook.yearnfinance'
export const PLUGIN_META_KEY = 'com.maskbook.yearnfinance:1'
export const PLUGIN_NAME = 'Yearn Finance'
export const PLUGIN_ICON = 'YF'
export const PLUGIN_DESCRIPTION = 'Yearn Finance on Mask Network.'
