export const MASK_STORAGE_KEY = 'com.mask.plugin'
export const KV_BASE_URL_DEV = 'https://kv-service.nextnext.id'
export const KV_BASE_URL_PROD = ''
export const PROOF_BASE_URL_DEV = 'https://proof-service.nextnext.id/'
export const PROOF_BASE_URL_PROD = 'https://proof-service.next.id/'
