export const KV_BASE_URL_DEV = 'https://kv-service.nextnext.id'
export const KV_BASE_URL_PROD = 'https://kv-service.next.id'
export const PROOF_BASE_URL_DEV = 'https://proof-service.nextnext.id/'
export const PROOF_BASE_URL_PROD = 'https://proof-service.next.id/'
export const RELATION_SERVICE_URL = 'https://relation-service-tiger.next.id'
