import type { Web3Plugin } from '@masknet/plugin-infra'
import { ChainId, NetworkType, ProviderType } from '@masknet/web3-shared-evm'

export const PLUGIN_META_KEY = 'com.mask.evm'
export const PLUGIN_ID = 'com.mask.evm'
export const PLUGIN_NAME = 'EVM'
export const PLUGIN_ICON = 'Ξ'
export const PLUGIN_DESCRIPTION = ''
export const PLUGIN_NETWORKS: Web3Plugin.NetworkDescriptor[] = [
    {
        ID: `${PLUGIN_ID}_ethereum`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: ChainId.Mainnet,
        type: NetworkType.Ethereum,
        name: 'Ethereum',
        icon: new URL('./assets/ethereum.png', import.meta.url),
        iconColor: 'rgb(28, 104, 243)',
        isMainnet: true,
    },
    {
        ID: `${PLUGIN_ID}_ropsten`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: ChainId.Ropsten,
        type: NetworkType.Ethereum,
        name: 'Ropsten',
        icon: new URL('./assets/ethereum.png', import.meta.url),
        iconColor: 'rgb(255, 65, 130)',
        isMainnet: false,
    },
    {
        ID: `${PLUGIN_ID}_kovan`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: ChainId.Kovan,
        type: NetworkType.Ethereum,
        name: 'Kovan',
        icon: new URL('./assets/ethereum.png', import.meta.url),
        iconColor: 'rgb(133, 89, 255)',
        isMainnet: false,
    },
    {
        ID: `${PLUGIN_ID}_rinkeby`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: ChainId.Rinkeby,
        type: NetworkType.Ethereum,
        name: 'Rinkeby',
        icon: new URL('./assets/ethereum.png', import.meta.url),
        iconColor: 'rgb(133, 89, 255)',
        isMainnet: false,
    },
    {
        ID: `${PLUGIN_ID}_gorli`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: ChainId.Gorli,
        type: NetworkType.Ethereum,
        name: 'Görli',
        icon: new URL('./assets/ethereum.png', import.meta.url),
        iconColor: 'rgb(48, 153, 242)',
        isMainnet: false,
    },
    {
        ID: `${PLUGIN_ID}_bsc`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: ChainId.BSC,
        type: NetworkType.Binance,
        name: 'BSC',
        icon: new URL('./assets/binance.png', import.meta.url),
        iconColor: 'rgb(240, 185, 10)',
        isMainnet: true,
    },
    {
        ID: `${PLUGIN_ID}_bsct`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: ChainId.BSC,
        type: NetworkType.Binance,
        name: 'BSCT',
        icon: new URL('./assets/binance.png', import.meta.url),
        iconColor: 'rgb(240, 185, 10)',
        isMainnet: false,
    },
    {
        ID: `${PLUGIN_ID}_polygon`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: ChainId.Matic,
        type: NetworkType.Polygon,
        name: 'Polygon',
        icon: new URL('./assets/polygon.png', import.meta.url),
        iconColor: 'rgb(119, 62, 225)',
        isMainnet: true,
    },
    {
        ID: `${PLUGIN_ID}_mumbai`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: ChainId.Mumbai,
        type: NetworkType.Polygon,
        name: 'Mumbai',
        icon: new URL('./assets/polygon.png', import.meta.url),
        iconColor: 'rgb(119, 62, 225)',
        isMainnet: false,
    },
    {
        ID: `${PLUGIN_ID}_arbitrum`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: ChainId.Arbitrum,
        type: NetworkType.Arbitrum,
        name: 'Arbitrum One',
        icon: new URL('./assets/arbitrum.png', import.meta.url),
        iconColor: 'rgb(36, 150, 238)',
        isMainnet: true,
    },
    {
        ID: `${PLUGIN_ID}_arbitrum_rinkeby`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: ChainId.Arbitrum_Rinkeby,
        type: NetworkType.Arbitrum,
        name: 'Arbitrum Rinkeby',
        icon: new URL('./assets/arbitrum.png', import.meta.url),
        iconColor: 'rgb(36, 150, 238)',
        isMainnet: false,
    },
    {
        ID: `${PLUGIN_ID}_xdai`,
        networkSupporterPluginID: PLUGIN_ID,
        chainId: ChainId.xDai,
        type: NetworkType.xDai,
        name: 'xDai',
        icon: new URL('./assets/xdai.png', import.meta.url),
        iconColor: 'rgb(73, 169, 166)',
        isMainnet: true,
    },
]
export const PLUGIN_PROVIDERS: Web3Plugin.ProviderDescriptor[] = [
    {
        ID: `${PLUGIN_ID}_maskwallet`,
        providerAdaptorPluginID: PLUGIN_ID,
        type: ProviderType.MaskWallet,
        name: 'Mask Network',
        icon: new URL('./assets/maskwallet.png', import.meta.url),
    },
    {
        ID: `${PLUGIN_ID}_metamask`,
        providerAdaptorPluginID: PLUGIN_ID,
        type: ProviderType.MetaMask,
        name: 'MetaMask',
        icon: new URL('./assets/metamask.png', import.meta.url),
    },
    {
        ID: `${PLUGIN_ID}_walletconnect`,
        providerAdaptorPluginID: PLUGIN_ID,
        type: ProviderType.WalletConnect,
        name: 'WalletConnect',
        icon: new URL('./assets/walletconnect.png', import.meta.url),
    },
    {
        ID: `${PLUGIN_ID}_coin98`,
        providerAdaptorPluginID: PLUGIN_ID,
        type: ProviderType.Coin98,
        name: 'Coin98',
        icon: new URL('./assets/coin98.png', import.meta.url),
    },
    {
        ID: `${PLUGIN_ID}_walletlink`,
        providerAdaptorPluginID: PLUGIN_ID,
        type: ProviderType.WalletLink,
        name: 'Coinbase',
        icon: new URL('./assets/coinbase.png', import.meta.url),
    },
    {
        ID: `${PLUGIN_ID}_mathwallet`,
        providerAdaptorPluginID: PLUGIN_ID,
        type: ProviderType.MathWallet,
        name: 'MathWallet',
        icon: new URL('./assets/mathwallet.png', import.meta.url),
    },
    {
        ID: `${PLUGIN_ID}_fortmatic`,
        providerAdaptorPluginID: PLUGIN_ID,
        type: ProviderType.Fortmatic,
        name: 'Fortmatic',
        icon: new URL('./assets/fortmatic.png', import.meta.url),
    },
]
export const PLUGIN_APPLICATIONS: Web3Plugin.ApplicationDescriptor[] = [
    {
        ID: `${PLUGIN_ID}_application_redpacket`,
        name: 'Lucky Drop',
        icon: new URL('./assets/lucky_drop.png', import.meta.url),
    },
]
export const PLUGIN_APPLICATION_CATEGORIES: Web3Plugin.ApplicationCategoryDescriptor[] = [
    {
        ID: `${PLUGIN_ID}_category_nfts`,
        name: 'NFTs',
        icon: new URL('./assets/nfts.png', import.meta.url),
    },
]
