// If your plugin also works in isolated dashboard, please also register it in
// packages/dashboard/src/initialization/plugins.ts

import '@masknet/plugin-example'
import '../plugins/Wallet'
import '../plugins/RedPacket'
import '../plugins/ITO'
import '../plugins/Snapshot'
import '../plugins/Collectible'
import '../plugins/External'
import '../plugins/Transak'
import '../plugins/Gitcoin'
import '../plugins/Polls'
import '../plugins/FileService'
import '../plugins/VCent'
import '../plugins/Trader'
import '../plugins/dHEDGE'
import '../plugins/PoolTogether'
import '../plugins/GoodGhosting'
import '../plugins/UnlockProtocol'
import '../plugins/Entropyfi'
// import '../plugins/NFT'
// import '../plugins/Airdrop'
