name: Build

on:
  push:
    branches: [master, develop, released]
  pull_request:
    branches: [master, develop, released]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Get cache date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-node-
      - uses: actions/cache@v2
        with:
          path: "packages/**/dist/"
          key: ${{ runner.os }}-tsc-${{ hashFiles('packages/**/tsconfig.json') }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-tsc-${{ hashFiles('packages/**/tsconfig.json') }}-${{ hashFiles('pnpm-lock.yaml') }}
            ${{ runner.os }}-tsc-${{ hashFiles('packages/**/tsconfig.json') }}
      - uses: actions/cache@v2
        with:
          path: ./packages/maskbook/node_modules/.cache/webpack/
          key: ${{ runner.os }}-webpack-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ steps.get-date.outputs.date }}
          # Not fallback to different dependencies. Webpack seems like have bug.
          # An example caused by the webpack cache bug: https://github.com/facebook/react/issues/21587
          restore-keys: |
            ${{ runner.os }}-webpack-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: npx pnpm install
      - run: npx build-ci
      - name: Upload `Maskbook.base.zip`
        uses: actions/upload-artifact@v2
        with:
          name: Maskbook.base.zip
          path: Maskbook.base.zip
      - name: Upload `Maskbook.iOS.zip`
        uses: actions/upload-artifact@v2
        with:
          name: Maskbook.iOS.zip
          path: Maskbook.iOS.zip
      - name: Upload `Maskbook.chromium.zip`
        uses: actions/upload-artifact@v2
        with:
          name: Maskbook.chromium.zip
          path: Maskbook.chromium.zip
      - name: Upload `Maskbook.chromium-beta.zip`
        uses: actions/upload-artifact@v2
        with:
          name: Maskbook.chromium-beta.zip
          path: Maskbook.chromium-beta.zip
      - name: Upload `Maskbook.firefox.zip`
        uses: actions/upload-artifact@v2
        with:
          name: Maskbook.firefox.zip
          path: Maskbook.firefox.zip
      - name: Upload `Maskbook.gecko.zip`
        uses: actions/upload-artifact@v2
        with:
          name: Maskbook.gecko.zip
          path: Maskbook.gecko.zip
