name: Changeset

on:
  push:
    branches:
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Changeset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: blob:none
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - name: Authenticate NPM
        uses: DimensionDev/github-token-action@latest
        with:
            registry: true
      - run: git config --global url."https://github.com/".insteadOf git@github.com
      - run: pnpm install
      - uses: changesets/action@v1
        with:
          publish: npx gulp changeset-release
          commit: "chore: changeset release"
          title: "chore: changeset release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
