name: Linters and tests

on:
  push:
    branches: [master, released]
  pull_request:
    branches: [master, released]

jobs:
  type-checking:
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v2-beta
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Type Checking
        run: yarn tsc --noEmitOnError
      - name: Type Coverage
        run: yarn lint:typecoverage
      - name: Locale Checking
        run: yarn locale-kit
      - name: Prettier Checking
        run: yarn prettier --check .
  eslint:
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v2-beta
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install
        run: yarn install --frozen-lockfile
      - name: ESLint
        run: yarn lint:report
      - name: Upload ESLint Report
        uses: actions/upload-artifact@v1
        with:
          name: eslint
          path: ./reports/junit
  storybook:
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v2-beta
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build Storybook
        run: yarn build-storybook
      - name: Upload Storybook output
        uses: actions/upload-artifact@v1
        with:
          name: storybook
          path: ./storybook-static
