name: Linters and tests

on:
  push:
    branches: [master, released]
  pull_request:
    branches: [master, released]

jobs:
  linters:
    runs-on: ubuntu-20.04
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v2-beta
      - run: echo "::set-output name=dir::$(npm get cache)"
      - run: sudo npm i -g npm@7
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
      - run: npm ci
      - run: npx prettier --check .
      - run: npx tsc -- --noEmitOnError
      - run: npm run lint:typecoverage
      - run: npm run locale-kit
      - run: npm run lint:report
      - name: Upload ESLint Report
        uses: actions/upload-artifact@v1
        with:
          name: eslint
          path: ./reports/junit
  storybook:
    runs-on: ubuntu-20.04
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v2-beta
      - run: echo "::set-output name=dir::$(npm get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
      - run: sudo npm i -g npm@7
      - run: npm ci
      - run: npm run build-storybook
      - uses: actions/upload-artifact@v1
        with:
          name: storybook
          path: ./storybook-static
