name: Deploy i18n locales

on:
  push:
    branches: [develop]

permissions:
  contents: write
  pull-requests: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Copy Files
        run: |
          mkdir i18n-locales
          find packages -type f -name "*.json" | grep locales | xargs -I {} rsync -R {} ./i18n-locales

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: i18n-locales
