name: "Check Jira Issue Key"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  merge_group:
    types: [checks_requested]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: DimensionDev/jira-issue-key-checker@master
        if: ${{ github.event.pull_request  }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          jira-prefix: 'MF|FW'
