name: Linters and tests

on:
  push:
    branches: [master, develop, released, hotfix/*, release/*]
  pull_request:
    branches: [master, develop, released, hotfix/*, release/*]
  merge_group:
    types: [checks_requested]

permissions:
  contents: read
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GGITHUB_TOKEN }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - name: Authenticate NPM
        uses: DimensionDev/github-token-action@latest
        with:
            registry: true
      - run: pnpm install
      - run: pnpx anti-trojan-source --files='packages/**/src/**/*.{ts,tsx,js}'
      - run: pnpx markdownlint-cli --fix .
      - run: pnpm exec gulp codegen
      - run: pnpm run lingui:extract
      - run: pnpm run lingui:compile
      - run: pnpm exec gulp lint-package-json
      - run: pnpm exec gulp fix-plugins-tsconfig
      - run: pnpx prettier@3.6.2 --write .
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'fix: linter'
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - name: Authenticate NPM
        uses: DimensionDev/github-token-action@latest
        with:
            registry: true
      - run: git config --global url."https://github.com/".insteadOf git@github.com
      - run: pnpm install
      - run: pnpm exec gulp codegen
      - run: pnpm exec gulp typescript
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - name: Authenticate NPM
        uses: DimensionDev/github-token-action@latest
        with:
            registry: true
      - run: git config --global url."https://github.com/".insteadOf git@github.com
      - run: pnpm install
      - run: pnpm exec gulp codegen
      - run: pnpm exec gulp polyfill
      - run: pnpm run test
  eslint:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GGITHUB_TOKEN }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - name: Authenticate NPM
        uses: DimensionDev/github-token-action@latest
        with:
            registry: true
      - name: Get cache date
        id: get-date
        run: echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_STATE
        shell: bash
      - name: Restore ESLint cache
        uses: actions/cache@v4
        with:
          path: .eslintcache
          key: linter-v2-${{ steps.get-date.outputs.date }}
          restore-keys: linter-v2-
      - run: git config --global url."https://github.com/".insteadOf git@github.com
      - run: pnpm install
      - run: pnpm exec gulp codegen
      - name: Run Eslint
        run: |
          export NODE_OPTIONS="--max-old-space-size=8192"
          # report to stdio and to a file, it's cached so the second run should be fast
          pnpm run lint:ci
          pnpm run lint:ci-report
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'fix: eslint'
      - name: Upload eslint report
        uses: actions/upload-artifact@v4
        with:
          name: eslint
          path: reports/junit
