name: Linters and tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master / released branch
on:
    push:
        branches: [master, released]
    pull_request:
        branches: [master, released]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    linters:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2-beta
              with:
                  node-version: 14
            - name: Install
              run: yarn install --link-duplicates --frozen-lockfile --pure-lockfile
            - name: TypeScript type check
              run: yarn tsc --noEmitOnError
            - name: Type coverage
              run: yarn lint:typecoverage
            - name: ESLint
              run: yarn lint:report
            - name: Import linter
              run: yarn ts-node -T ./scripts/import-linter.ts
            - name: ESLint result
              uses: actions/upload-artifact@v1
              with:
                  name: eslint
                  path: ./reports/junit
    storybook:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2-beta
              with:
                  node-version: 14
            - name: Install
              run: yarn install --link-duplicates --frozen-lockfile --pure-lockfile
            - name: Build storybook
              run: yarn build-storybook
            - name: Storybook output
              uses: actions/upload-artifact@v1
              with:
                  name: storybook
                  path: ./storybook-static
    e2e-tests:
        runs-on: self-hosted

        needs: [linters, storybook]

        container:
            image: differui/node-14.4.0-browsers:v1

            # more: https://github.community/t/how-to-run-action-as-a-non-root-user/17572/2#M6330
            options: |
                --user 1000
                -v /home/ubuntu/.cache/yarn/v6:/tmp/.yarn-cache-1000/v6
                -v /home/ubuntu/.cache/alice_home:/tmp/alice_home
                -v /home/ubuntu/.cache/bob_home:/tmp/bob_home
                -v /home/ubuntu/.e2e/e2e-test:/tmp/e2e-test

            # more: https://stackoverflow.com/a/60202672/1986338
            # volumes:
            #     - /home/ubuntu/.cache/yarn/v6:/tmp/.yarn-cache-1000/v6
            #     - /home/ubuntu/.cache/alice_home:/tmp/alice_home
            #     - /home/ubuntu/.cache/bob_home:/tmp/bob_home
            #     - /home/ubuntu/.e2e/e2e-test:/tmp/e2e-test
        steps:
            # - name: Debug
            #   run: |
            #       pwd
            #       ls /tmp/alice_home
            #       ls /tmp/bob_home
            #       ls -alh

            # @v2 requires too much configurations
            - uses: actions/checkout@v1

            - name: Install Dependencies
              run: |
                  yarn config set cache-folder /tmp/.yarn-cache-1000/v6
                  yarn install --link-duplicates --frozen-lockfile --pure-lockfile

            - name: Build
              run: yarn build:e2e

            - name: Setup E2E
              run: |
                  mkdir -p ./.env
                  cp /tmp/e2e-test ./.env/e2e-test
                  mkdir -p ./screenshots

            - name: Jest E2E
              run: xvfb-run --server-args="-screen 0 1366x768x24" yarn test:e2e

            - name: Teardown E2E
              run: rm -rf ./build

            - name: Archive Artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: screenshots
                  path: ./screenshots
