/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from 'bn.js'
import type { ContractOptions } from 'web3-eth-contract'
import type { EventLog } from 'web3-core'
import type { EventEmitter } from 'events'
import type {
    Callback,
    PayableTransactionObject,
    NonPayableTransactionObject,
    BlockType,
    ContractEventLog,
    BaseContract,
} from './types.js'

export interface EventOptions {
    filter?: object
    fromBlock?: BlockType
    topics?: string[]
}

export interface Create2Factory extends BaseContract {
    constructor(jsonInterface: any[], address?: string, options?: ContractOptions): Create2Factory
    clone(): Create2Factory
    methods: {
        fund(owner: string, nonce: number | string | BN): NonPayableTransactionObject<void>

        deploy(initCode: string | number[], salt: string | number[]): NonPayableTransactionObject<string>
    }
    events: {
        allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter
    }
}
