/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from 'bn.js'
import { ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import {
    Callback,
    PayableTransactionObject,
    NonPayableTransactionObject,
    BlockType,
    ContractEventLog,
    BaseContract,
} from './types'

interface EventOptions {
    filter?: object
    fromBlock?: BlockType
    topics?: string[]
}

export type AdminChanged = ContractEventLog<{
    previousAdmin: string
    newAdmin: string
    0: string
    1: string
}>
export type Upgraded = ContractEventLog<{
    implementation: string
    0: string
}>

export interface IdeaMarketLockProxy extends BaseContract {
    constructor(jsonInterface: any[], address?: string, options?: ContractOptions): IdeaMarketLockProxy
    clone(): IdeaMarketLockProxy
    methods: {
        admin(): NonPayableTransactionObject<string>

        changeAdmin(newAdmin: string): NonPayableTransactionObject<void>

        implementation(): NonPayableTransactionObject<string>

        upgradeTo(newImplementation: string): NonPayableTransactionObject<void>

        upgradeToAndCall(newImplementation: string, data: string | number[]): PayableTransactionObject<void>

        lock(ideaToken: string, amount: number, duration: number, recipient: string): NonPayableTransactionObject<void>
    }
    events: {
        AdminChanged(cb?: Callback<AdminChanged>): EventEmitter
        AdminChanged(options?: EventOptions, cb?: Callback<AdminChanged>): EventEmitter

        Upgraded(cb?: Callback<Upgraded>): EventEmitter
        Upgraded(options?: EventOptions, cb?: Callback<Upgraded>): EventEmitter

        allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter
    }

    once(event: 'AdminChanged', cb: Callback<AdminChanged>): void
    once(event: 'AdminChanged', options: EventOptions, cb: Callback<AdminChanged>): void

    once(event: 'Upgraded', cb: Callback<Upgraded>): void
    once(event: 'Upgraded', options: EventOptions, cb: Callback<Upgraded>): void
}
