/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from 'bn.js'
import type { ContractOptions } from 'web3-eth-contract'
import type { EventLog } from 'web3-core'
import type { EventEmitter } from 'events'
import type {
    Callback,
    PayableTransactionObject,
    NonPayableTransactionObject,
    BlockType,
    ContractEventLog,
    BaseContract,
} from './types.js'

export interface EventOptions {
    filter?: object
    fromBlock?: BlockType
    topics?: string[]
}

export interface MaskBoxQualification extends BaseContract {
    constructor(jsonInterface: any[], address?: string, options?: ContractOptions): MaskBoxQualification
    clone(): MaskBoxQualification
    methods: {
        is_qualified(
            account: string,
            proof: string | number[],
        ): NonPayableTransactionObject<{
            qualified: boolean
            error_msg: string
            0: boolean
            1: string
        }>

        version(): NonPayableTransactionObject<string>
    }
    events: {
        allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter
    }
}
