/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from 'bn.js'
import { ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import {
    Callback,
    PayableTransactionObject,
    NonPayableTransactionObject,
    BlockType,
    ContractEventLog,
    BaseContract,
} from './types'

interface EventOptions {
    filter?: object
    fromBlock?: BlockType
    topics?: string[]
}

export type FarmDepositChange = ContractEventLog<{
    farmHash: string
    delta: string
    isNegative: boolean
    0: string
    1: string
    2: boolean
}>
export type FarmExists = ContractEventLog<{
    sponsor: string
    rewardTokenDefn: string
    referredTokenDefn: string
    farmHash: string
    0: string
    1: string
    2: string
    3: string
}>
export type FarmMetastate = ContractEventLog<{
    farmHash: string
    key: string
    value: string
    0: string
    1: string
    2: string
}>
export type FarmTokenChange = ContractEventLog<{
    farmHash: string
    token: string
    change: string
    0: string
    1: string
    2: string
}>
export type OwnershipTransferred = ContractEventLog<{
    previousOwner: string
    newOwner: string
    0: string
    1: string
}>
export type RewardsHarvested = ContractEventLog<{
    caller: string
    rewardTokenDefn: string
    farmHash: string
    value: string
    leafHash: string
    0: string
    1: string
    2: string
    3: string
    4: string
}>

export interface ReferralFarmsV1 extends BaseContract {
    constructor(jsonInterface: any[], address?: string, options?: ContractOptions): ReferralFarmsV1
    clone(): ReferralFarmsV1
    methods: {
        configure(confirmationsAddr_: string): NonPayableTransactionObject<void>

        configureMetastate(
            rewardTokenDefn: string | number[],
            referredTokenDefn: string | number[],
            metastate: [string | number[], string | number[]][],
        ): NonPayableTransactionObject<void>

        devRescueErc20(token: string, value: number | string | BN, to: string): NonPayableTransactionObject<void>

        devRescueNative(value: number | string | BN, to: string): NonPayableTransactionObject<void>

        getAccountNonce(account: string): NonPayableTransactionObject<string>

        getFarmDepositRemaining(farmHash: string | number[]): NonPayableTransactionObject<string>

        getFarmPeriodReward(
            farmHash: string | number[],
            idx: number | string | BN,
        ): NonPayableTransactionObject<[string, string]>

        getFarmReferredTokenStatus(
            farmHash: string | number[],
            referredTokenDefn: string | number[],
        ): NonPayableTransactionObject<string>

        harvestRewards(
            reqs: [string | number[], number | string | BN, string | number[], number | string | BN][],
            proofs: (string | number[])[][],
            skipEffectNonces: (number | string | BN)[],
        ): NonPayableTransactionObject<void>

        increaseReferralFarm(
            rewardToken: string | number[],
            referredTokenDefn: string | number[],
            rewardDeposit: number | string | BN,
            metastate: [string | number[], string | number[]][],
        ): NonPayableTransactionObject<void>

        owner(): NonPayableTransactionObject<string>

        renounceOwnership(): NonPayableTransactionObject<void>

        transferOwnership(newOwner: string): NonPayableTransactionObject<void>
    }
    events: {
        FarmDepositChange(cb?: Callback<FarmDepositChange>): EventEmitter
        FarmDepositChange(options?: EventOptions, cb?: Callback<FarmDepositChange>): EventEmitter

        FarmExists(cb?: Callback<FarmExists>): EventEmitter
        FarmExists(options?: EventOptions, cb?: Callback<FarmExists>): EventEmitter

        FarmMetastate(cb?: Callback<FarmMetastate>): EventEmitter
        FarmMetastate(options?: EventOptions, cb?: Callback<FarmMetastate>): EventEmitter

        FarmTokenChange(cb?: Callback<FarmTokenChange>): EventEmitter
        FarmTokenChange(options?: EventOptions, cb?: Callback<FarmTokenChange>): EventEmitter

        OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter
        OwnershipTransferred(options?: EventOptions, cb?: Callback<OwnershipTransferred>): EventEmitter

        RewardsHarvested(cb?: Callback<RewardsHarvested>): EventEmitter
        RewardsHarvested(options?: EventOptions, cb?: Callback<RewardsHarvested>): EventEmitter

        allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter
    }

    once(event: 'FarmDepositChange', cb: Callback<FarmDepositChange>): void
    once(event: 'FarmDepositChange', options: EventOptions, cb: Callback<FarmDepositChange>): void

    once(event: 'FarmExists', cb: Callback<FarmExists>): void
    once(event: 'FarmExists', options: EventOptions, cb: Callback<FarmExists>): void

    once(event: 'FarmMetastate', cb: Callback<FarmMetastate>): void
    once(event: 'FarmMetastate', options: EventOptions, cb: Callback<FarmMetastate>): void

    once(event: 'FarmTokenChange', cb: Callback<FarmTokenChange>): void
    once(event: 'FarmTokenChange', options: EventOptions, cb: Callback<FarmTokenChange>): void

    once(event: 'OwnershipTransferred', cb: Callback<OwnershipTransferred>): void
    once(event: 'OwnershipTransferred', options: EventOptions, cb: Callback<OwnershipTransferred>): void

    once(event: 'RewardsHarvested', cb: Callback<RewardsHarvested>): void
    once(event: 'RewardsHarvested', options: EventOptions, cb: Callback<RewardsHarvested>): void
}
