/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from 'bn.js'
import { ContractOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import {
    Callback,
    PayableTransactionObject,
    NonPayableTransactionObject,
    BlockType,
    ContractEventLog,
    BaseContract,
} from './types'

interface EventOptions {
    filter?: object
    fromBlock?: BlockType
    topics?: string[]
}

export interface ShoyuEnglishAuction extends BaseContract {
    constructor(jsonInterface: any[], address?: string, options?: ContractOptions): ShoyuEnglishAuction
    clone(): ShoyuEnglishAuction
    methods: {
        canBid(
            proxy: string,
            deadline: number | string | BN,
            params: string | number[],
            arg3: string,
            bidPrice: number | string | BN,
            arg5: string,
            bestBidPrice: number | string | BN,
            arg7: number | string | BN,
        ): NonPayableTransactionObject<boolean>

        canClaim(
            proxy: string,
            deadline: number | string | BN,
            params: string | number[],
            bidder: string,
            bidPrice: number | string | BN,
            bestBidder: string,
            bestBidPrice: number | string | BN,
            arg7: number | string | BN,
        ): NonPayableTransactionObject<boolean>
    }
    events: {
        allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter
    }
}
